// src/content/homework/vocab-list.ts
// 竹光國中 2026 新生暑假作業「英文單字表」的完整單字清單。
//
// 來源：參考文件/竹光2026暑假作業.pdf 第 5–7 頁。原 PDF 是掃描檔，
// OCR 有不少錯字（例 ApIi l→April、aim→arm、smg→sing、p1g→pig…），
// 這裡已逐字對照「國小常用字」校正成正確拼法，因為這份作業的目標是
// 「確保每個單字都拼得對」，拼法一定要正確。
//
// 出題方式：看中文、拼英文。同一個中文對應多個英文時（看 = look/watch/see），
// 在 vocab.ts 會合併成一張卡，拼出任一個就算對。
// 批改採 normalize（轉小寫、去空白/標點），所以大小寫、空白、句點都容錯，
// 只看字母對不對（T-shirt = tshirt、P.E. = pe、ice cream = icecream）。

import type { RawVocab } from "./types";

export const RAW_VOCAB: RawVocab[] = [
  // A
  { en: "a", zh: "一個" },
  { en: "an", zh: "一個" },
  { en: "afternoon", zh: "下午" },
  { en: "and", zh: "和" },
  { en: "angry", zh: "生氣的" },
  { en: "animal", zh: "動物" },
  { en: "apple", zh: "蘋果" },
  { en: "April", zh: "四月" },
  { en: "arm", zh: "手臂" },
  { en: "art", zh: "美術" },
  { en: "at", zh: "在（某地點）" },
  { en: "August", zh: "八月" },

  // B
  { en: "bad", zh: "壞的" },
  { en: "bag", zh: "袋子" },
  { en: "ball", zh: "球" },
  { en: "banana", zh: "香蕉" },
  { en: "baseball", zh: "棒球" },
  { en: "basketball", zh: "籃球" },
  { en: "bathroom", zh: "浴室" },
  { en: "bear", zh: "熊" },
  { en: "beautiful", zh: "漂亮的" },
  { en: "bed", zh: "床" },
  { en: "bedroom", zh: "臥室" },
  { en: "big", zh: "大的" },
  { en: "bike", zh: "單車" },
  { en: "bird", zh: "鳥" },
  { en: "birthday", zh: "生日" },
  { en: "black", zh: "黑色" },
  { en: "blue", zh: "藍色" },
  { en: "book", zh: "書" },
  { en: "book bag", zh: "書包" },
  { en: "bookstore", zh: "書店" },
  { en: "box", zh: "盒子" },
  { en: "boy", zh: "男孩" },
  { en: "bread", zh: "麵包" },
  { en: "breakfast", zh: "早餐" },
  { en: "brother", zh: "兄弟" },
  { en: "brown", zh: "棕色" },
  { en: "bus", zh: "公車；巴士" },
  { en: "by", zh: "在…旁邊" },

  // C
  { en: "cake", zh: "蛋糕" },
  { en: "can", zh: "能；可以" },
  { en: "car", zh: "汽車" },
  { en: "cat", zh: "貓" },
  { en: "CD", zh: "CD 唱片" },
  { en: "chair", zh: "椅子" },
  { en: "chicken", zh: "雞；小雞" },
  { en: "Chinese", zh: "中文" },
  { en: "classmate", zh: "同學" },
  { en: "classroom", zh: "教室" },
  { en: "clean", zh: "乾淨的" },
  { en: "close", zh: "關上" },
  { en: "cloudy", zh: "多雲的" },
  { en: "cold", zh: "冷的" },
  { en: "color", zh: "顏色" },
  { en: "come", zh: "來" },
  { en: "comic book", zh: "漫畫書" },
  { en: "computer", zh: "電腦" },
  { en: "cook", zh: "煮；廚師" },
  { en: "cool", zh: "涼爽的" },
  { en: "cut", zh: "切" },
  { en: "cute", zh: "可愛的" },

  // D
  { en: "dad", zh: "爸爸" },
  { en: "dance", zh: "跳舞" },
  { en: "day", zh: "天；日子" },
  { en: "December", zh: "十二月" },
  { en: "desk", zh: "書桌" },
  { en: "dinner", zh: "晚餐" },
  { en: "do", zh: "做" },
  { en: "doctor", zh: "醫生" },
  { en: "dodgeball", zh: "躲避球", accept: ["dodge ball"] },
  { en: "does", zh: "做（第三人稱）" },
  { en: "dog", zh: "狗" },
  { en: "dollar", zh: "元（錢）" },
  { en: "draw", zh: "畫畫" },
  { en: "dress", zh: "洋裝" },
  { en: "drink", zh: "喝" },

  // E
  { en: "ear", zh: "耳朵" },
  { en: "eat", zh: "吃" },
  { en: "egg", zh: "蛋" },
  { en: "eight", zh: "八（8）" },
  { en: "elephant", zh: "大象" },
  { en: "eleven", zh: "十一（11）" },
  { en: "English", zh: "英文" },
  { en: "eraser", zh: "橡皮擦" },
  { en: "evening", zh: "傍晚" },
  { en: "eye", zh: "眼睛" },

  // F
  { en: "fall", zh: "秋天" },
  { en: "fat", zh: "胖的" },
  { en: "father", zh: "爸爸" },
  { en: "February", zh: "二月" },
  { en: "feet", zh: "腳（複數）" },
  { en: "fine", zh: "美好的" },
  { en: "fish", zh: "魚" },
  { en: "five", zh: "五（5）" },
  { en: "flower", zh: "花" },
  { en: "fly", zh: "飛" },
  { en: "foot", zh: "腳（單數）" },
  { en: "four", zh: "四（4）" },
  { en: "Friday", zh: "星期五" },
  { en: "friend", zh: "朋友" },

  // G
  { en: "get up", zh: "起床" },
  { en: "girl", zh: "女孩" },
  { en: "go", zh: "去" },
  { en: "good", zh: "好的" },
  { en: "goodbye", zh: "再見" },
  { en: "grandfather", zh: "祖父；外公" },
  { en: "grandma", zh: "祖母；外婆（口語）" },
  { en: "grandmother", zh: "祖母；外婆" },
  { en: "grandpa", zh: "祖父；外公（口語）" },
  { en: "great", zh: "很棒" },
  { en: "green", zh: "綠色" },

  // H
  { en: "hair", zh: "頭髮" },
  { en: "hamburger", zh: "漢堡" },
  { en: "hand", zh: "手" },
  { en: "handsome", zh: "英俊的" },
  { en: "happy", zh: "快樂的" },
  { en: "hat", zh: "帽子" },
  { en: "he", zh: "他" },
  { en: "he has", zh: "他有" },
  { en: "he is", zh: "他是；她是", accept: ["she is"] },
  { en: "head", zh: "頭" },
  { en: "hello", zh: "哈囉" },
  { en: "help", zh: "幫助" },
  { en: "her", zh: "她的" },
  { en: "here", zh: "這裡" },
  { en: "his", zh: "他的" },
  { en: "home", zh: "家" },
  { en: "hot", zh: "熱的" },
  { en: "hot dog", zh: "熱狗" },
  { en: "how", zh: "如何；怎樣" },
  { en: "hungry", zh: "飢餓的" },

  // I
  { en: "I", zh: "我" },
  { en: "I am", zh: "我是" },
  { en: "I have", zh: "我有" },
  { en: "ice cream", zh: "冰淇淋" },
  { en: "in", zh: "在…裡面" },
  { en: "it", zh: "它；牠" },

  // J
  { en: "jacket", zh: "夾克" },
  { en: "January", zh: "一月" },
  { en: "juice", zh: "果汁" },
  { en: "July", zh: "七月" },
  { en: "June", zh: "六月" },

  // K
  { en: "key", zh: "鑰匙" },
  { en: "kitchen", zh: "廚房" },
  { en: "kite", zh: "風箏" },

  // L
  { en: "leg", zh: "腿" },
  { en: "library", zh: "圖書館" },
  { en: "like", zh: "喜歡" },
  { en: "lion", zh: "獅子" },
  { en: "living room", zh: "客廳" },
  { en: "listen", zh: "聽" },
  { en: "long", zh: "長的" },
  { en: "look", zh: "看" },
  { en: "lunch", zh: "午餐" },

  // M
  { en: "March", zh: "三月" },
  { en: "marker", zh: "馬克筆" },
  { en: "math", zh: "數學" },
  { en: "May", zh: "五月" },
  { en: "may", zh: "可以（助動詞）" },
  { en: "me", zh: "我（受詞）" },
  { en: "meet", zh: "遇見" },
  { en: "milk", zh: "牛奶" },
  { en: "Monday", zh: "星期一" },
  { en: "monkey", zh: "猴子" },
  { en: "morning", zh: "早上" },
  { en: "mom", zh: "媽媽" },
  { en: "mother", zh: "媽媽" },
  { en: "mouth", zh: "嘴巴" },
  { en: "Mr.", zh: "先生" },
  { en: "my", zh: "我的" },

  // N
  { en: "name", zh: "名字" },
  { en: "new", zh: "新的" },
  { en: "nice", zh: "不錯的" },
  { en: "night", zh: "晚上" },
  { en: "nine", zh: "九（9）" },
  { en: "no", zh: "不" },
  { en: "nose", zh: "鼻子" },
  { en: "not", zh: "不是" },
  { en: "notebook", zh: "筆記本" },
  { en: "November", zh: "十一月" },

  // O
  { en: "October", zh: "十月" },
  { en: "OK", zh: "好的；沒問題" },
  { en: "old", zh: "舊的；老的" },
  { en: "on", zh: "在…上面" },
  { en: "one", zh: "一（1）" },
  { en: "open", zh: "打開" },
  { en: "orange", zh: "橘色" },
  { en: "out", zh: "向外" },
  { en: "outside", zh: "外面" },

  // P
  { en: "P.E.", zh: "體育（課）" },
  { en: "park", zh: "公園" },
  { en: "pen", zh: "筆" },
  { en: "pencil", zh: "鉛筆" },
  { en: "pencil box", zh: "鉛筆盒" },
  { en: "pig", zh: "豬" },
  { en: "pink", zh: "粉紅色" },
  { en: "pizza", zh: "披薩" },
  { en: "play", zh: "玩" },
  { en: "purple", zh: "紫色" },

  // Q
  { en: "quiz", zh: "小考；測驗" },

  // R
  { en: "rabbit", zh: "兔子" },
  { en: "rainy", zh: "下雨的" },
  { en: "read", zh: "閱讀" },
  { en: "red", zh: "紅色" },
  { en: "ruler", zh: "尺" },
  { en: "run", zh: "跑" },

  // S
  { en: "sad", zh: "悲傷的" },
  { en: "sandwich", zh: "三明治" },
  { en: "Saturday", zh: "星期六" },
  { en: "school", zh: "學校" },
  { en: "see", zh: "看見" },
  { en: "September", zh: "九月" },
  { en: "seven", zh: "七（7）" },
  { en: "she", zh: "她" },
  { en: "shirt", zh: "襯衫" },
  { en: "shoes", zh: "鞋子" },
  { en: "short", zh: "矮的；短的" },
  { en: "shorts", zh: "短褲" },
  { en: "sick", zh: "生病的" },
  { en: "sing", zh: "唱歌" },
  { en: "sister", zh: "姊妹" },
  { en: "six", zh: "六（6）" },
  { en: "sleep", zh: "睡覺" },
  { en: "small", zh: "小的" },
  { en: "smart", zh: "聰明的" },
  { en: "snake", zh: "蛇" },
  { en: "some", zh: "一些" },
  { en: "sorry", zh: "抱歉的" },
  { en: "soup", zh: "湯" },
  { en: "spring", zh: "春天" },
  { en: "store", zh: "商店" },
  { en: "student", zh: "學生" },
  { en: "study", zh: "學習；讀書" },
  { en: "summer", zh: "夏天" },
  { en: "Sunday", zh: "星期日" },
  { en: "sunny", zh: "大太陽的" },
  { en: "supermarket", zh: "超級市場" },
  { en: "swim", zh: "游泳" },

  // T
  { en: "table", zh: "桌子" },
  { en: "take", zh: "拿" },
  { en: "talk", zh: "說話" },
  { en: "tall", zh: "高的" },
  { en: "taxi", zh: "計程車" },
  { en: "tea", zh: "茶" },
  { en: "teacher", zh: "老師" },
  { en: "telephone", zh: "電話" },
  { en: "ten", zh: "十（10）" },
  { en: "thank", zh: "謝謝" },
  { en: "that", zh: "那（個）" },
  { en: "the", zh: "這；那（定冠詞）" },
  { en: "there", zh: "那裡" },
  { en: "these", zh: "這些" },
  { en: "they", zh: "他們" },
  { en: "thin", zh: "瘦的" },
  { en: "this", zh: "這（個）" },
  { en: "those", zh: "那些" },
  { en: "three", zh: "三（3）" },
  { en: "Thursday", zh: "星期四" },
  { en: "tiger", zh: "老虎" },
  { en: "tired", zh: "疲倦的" },
  { en: "today", zh: "今天" },
  { en: "too", zh: "也；太" },
  { en: "toy", zh: "玩具" },
  { en: "train", zh: "火車" },
  { en: "tree", zh: "樹" },
  { en: "T-shirt", zh: "運動衫；T 恤" },
  { en: "Tuesday", zh: "星期二" },
  { en: "TV", zh: "電視" },
  { en: "twelve", zh: "十二（12）" },
  { en: "two", zh: "二（2）" },

  // U
  { en: "under", zh: "在…下面" },

  // V
  { en: "very", zh: "非常" },

  // W
  { en: "walk", zh: "走路" },
  { en: "want", zh: "想要" },
  { en: "warm", zh: "溫暖的" },
  { en: "wash", zh: "洗" },
  { en: "watch", zh: "觀看；手錶" },
  { en: "water", zh: "水" },
  { en: "way", zh: "道路；通路" },
  { en: "we", zh: "我們" },
  { en: "weather", zh: "天氣" },
  { en: "Wednesday", zh: "星期三" },
  { en: "what", zh: "什麼" },
  { en: "when", zh: "什麼時候" },
  { en: "where", zh: "在哪裡" },
  { en: "white", zh: "白色" },
  { en: "who", zh: "誰" },
  { en: "window", zh: "窗戶" },
  { en: "windy", zh: "有風的" },
  { en: "winter", zh: "冬天" },
  { en: "write", zh: "寫" },

  // X
  { en: "X-ray", zh: "X 光" },

  // Y
  { en: "yellow", zh: "黃色" },
  { en: "yes", zh: "是的；對" },
  { en: "you", zh: "你（們）" },
  { en: "you are", zh: "你是" },
  { en: "your", zh: "你的" },

  // Z
  { en: "zero", zh: "零（0）" },
  { en: "zoo", zh: "動物園" },
];
